apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: privileged-pod
  name: privileged-pod
spec:
  containers:
  - args:
    - sleep
    - "999999"
    image: alpine
    name: privileged-pod
    securityContext:
      privileged: true
      capabilities:
        drop: ["SYS_TIME"]
