apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: readonly-pod
  name: readonly-pod
spec:
  containers:
  - args:
    - sleep
    - "999999"
    image: alpine
    name: readonly-pod
    securityContext:
      readOnlyRootFilesystem: true
