apiVersion: v1
kind: Pod
metadata:
  labels:
    run: remove-capabilities-pod
  name: remove-capabilities-pod
spec:
  containers:
  - args:
    - sleep
    - "999999"
    image: alpine
    name: remove-capabilities-pod
    securityContext:
      capabilities:
        drop: ["SYS_TIME","CHOWN"]
