apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nonroot-pod
  name: nonroot-pod
spec:
  containers:
  - args:
    - sleep
    - "1000"
    image: busybox
    name: secure-pod
    securityContext:
      runAsNonRoot: True
