apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secure-pod
  name: secure-pod
spec:
  containers:
  - args:
    - sleep
    - "1000"
    image: alpine
    name: secure-pod
    securityContext:
      runAsUser: 1000
