apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-dev-read-only
  namespace: dev
subjects:
- kind: User
  name: talant
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: dev-read-only 
  apiGroup: rbac.authorization.k8s.io