apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web
  name: developer-group-role
rules:
- apiGroups: ["","apps"] 
  resources: ["deployments","replicasets","pods","secrets","configmaps"]
  verbs: ["create","update","get", "watch", "list"]