apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-group-role-binding
  namespace: web
subjects:
- kind: Group
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: developer-group-role 
  apiGroup: rbac.authorization.k8s.io