apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-dev-read-only
  namespace: web
subjects:
- kind: User
  name: kapar
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: web-read-only 
  apiGroup: rbac.authorization.k8s.io