apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-busybox
  name: my-busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      run: my-busybox
  template:
    metadata:
      labels:
        run: my-busybox
    spec:
      containers:
      - args:
        - sleep
        - "1000"
        image: busybox
        name: my-busybox
