apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: qa
  name: dev-read-only
rules:
- apiGroups: ["","apps"] 
  resources: ["deployments","replicasets","pods"]
  verbs: ["get", "watch", "list"]