apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-allows-busybox-to-access
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: busybox
    ports:
    - port: 80