apiVersion: v1
kind: Pod
metadata:
  name: db-app
  labels:
    app: app-db
    tier: backend
spec:
  containers:
    - image: mysql
      name: mysql-cont
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass@123