apiVersion: v1
kind: Pod
metadata: 
  name: kuard-pod
  labels:
    app: kuard
spec:
  containers:
    - image: ktalant/kuard:1
      name: private-container

  imagePullSecrets:
    - name: docker-cred