apiVersion: v1
kind: Pod
metadata: 
  name: ubuntu-sleeper
  labels:
    app: ubuntu
spec:
  containers:
    - image: ktalant/ubuntu-sleeper:v1
      name: private-container

  imagePullSecrets:
    - name: talant-docker-regcred